# Indicates docker image
FROM osrf/ros:noetic-desktop-full 

# Configure environment
ENV DISPLAY host.docker.internal:0.0

# Listens to port
EXPOSE 8080
EXPOSE 9090

# Install necessary packages
RUN apt-get update && \
    apt-get install -y x11-apps

# Copy source files
COPY ./ /root/catkin_ws/src/

# Copy installation scripts
COPY ./micebot_dockerfiles/install /root/install

# Run dependencies installation
RUN chmod +x /root/install/*
RUN sed -i -e 's/\r$//' /root/install/i_dep.sh
RUN /bin/sh -e -c /root/install/i_dep.sh

# Set default bash shell
SHELL ["/bin/bash", "-c"]

# Set start-up directory
WORKDIR /root/catkin_ws

# Source ROS setup and set environment variables
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "export ROS_MASTER_URI=http://localhost:11311" >> /root/.bashrc

# Build the catkin workspace (don't source directly in this layer)
RUN catkin_make

# Source the catkin workspace setup in the .bashrc (this will persist for interactive sessions)
RUN echo "source /root/catkin_ws/devel/setup.bash" >> ~/.bashrc

# Default command to start the container (opens a bash shell)
CMD ["bash"]